language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script: "ruby -e 'exit(0)'"
# more information on configuring openshift deployments
# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  # Configure these values on your TravisCI 'Repository Settings' page:
  # http://docs.travis-ci.com/user/environment-variables/#Using-Settings
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP_NAME
  domain: $OPENSHIFT_APP_NAMESPACE
